version: 2.1

commands:
  prepare_maven_environment:
    steps:
      - run:
          name: Importing Settings from Github
          command: |
            curl https://raw.githubusercontent.com/archmix/infra-maven/master/settings.xml >> settings.xml
      - run:
          name: Importing GPG Key
          command: |
            echo -e "$MAVEN_GPG_KEY" | gpg --import

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - prepare_maven_environment
      - run: mvn -s settings.xml clean deploy

  release:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - add_ssh_keys
      - checkout

      - prepare_maven_environment
      - run: git config user.email "ci@archmix.org"
      - run: git config user.name "Circle CI"
      - run: mvn -DskipTests -P release -B -s settings.xml release:clean release:prepare release:perform -DignoreSnapshots=true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Archmix
      - release:
          context: Archmix
          requires:
            - build
          filters:
            branches:
              only: master